INSTAVEL = {'INSTAVEL' : {

    'Número de Instabilidades por Código' :
     [{"x"       : "A_CODE", 
       "y"       : "Contigence", 
       "c"       : "", 
       "plot"    : "Bar", 
       "round"   : "",
       "stat"    : "Count",
       "x_label" : "Código",
       "y_label" : "Número de Instabilidades", 
       "legend"  : None, 
       "filter"  : [("A_CODE", '!=', 0)]}],

    'Barras Sensibilizadas por Contingências' : 
     [{"x"       : "B_STAB", 
       "y"       : "Contigence", 
       "c"       : "OP", 
       "plot"    : "HeatMap", 
       "round"   : "",
       "stat"    : "Count",
       "x_label" : "Contingências",
       "y_label" : "Barra", 
       "legend"  : None, 
       "filter"  : [("A_CODE", '!=', 0)]}],

    'Contingências com Instabilidade por Dia e Hora' :
     [{"x"       : "Hora", 
       "y"       : "Dia", 
       "c"       : "Contigence", 
       "plot"    : "HeatMap", 
       "round"   : "",
       "stat"    : "Count",
       "x_label" : "Hora",
       "y_label" : "Dia", 
       "legend"  : None, 
       "filter"  : [("A_CODE", '!=', 0)]}],

    'Número de POs com Instabilidade por Contingência' :
     [{"x"       : "Contigence", 
       "y"       : "OP", 
       "c"       : "", 
       "plot"    : "Bar", 
       "round"   : "",
       "stat"    : "Count",
       "x_label" : "Contingência",
       "y_label" : "Número de POs com Instabilidade", 
       "legend"  : None, 
       "filter"  : [("A_CODE", '!=', 0)]}],

    'Número de Instabilidades por Dia' : 
     [{"x"       : "Dia", 
       "y"       : "A_CODE", 
       "c"       : "", 
       "plot"    : "Bar", 
       "round"   : "",
       "stat"    : "Count",
       "x_label" : "Dia",
       "y_label" : "Número de Instabilidades", 
       "legend"  : None, 
       "filter"  : [("A_CODE", '!=', 0)]}],

    'Número de Instabilidades por Hora' :
     [{"x"       : "Hora", 
       "y"       : "A_CODE", 
       "c"       : "", 
       "plot"    : "Bar", 
       "round"   : "",
       "stat"    : "Count",
       "x_label" : "Hora",
       "y_label" : "Número de Instabilidades", 
       "legend"  : None, 
       "filter"  : [("A_CODE", '!=', 0)]}],
       
}}


ESTAVEL = {'ROCOF' : {

    'Distribuição do RoCoF por Contingência [1 a 9]' : 
     [{"x"       : "Contigence", 
       "y"       : "A_RCFC", 
       "c"       : "", 
       "plot"    : "Violin", 
       "round"   : "",
       "stat"    : "",
       "x_label" : "Contingência",
       "y_label" : "RoCoF", 
       "legend"  : None, 
       "filter"  : [("A_CODE"    , '==', 0),
                    ("Contigence", '>' , 0),
                    ("Contigence", '<=', 9)]}],


    'Distribuição do RoCoF por Contingência [10 a 18]' :
     [{"x"       : "Contigence", 
       "y"       : "A_RCFC", 
       "c"       : "", 
       "plot"    : "Violin", 
       "round"   : "",
       "stat"    : "",
       "x_label" : "Contingência",
       "y_label" : "RoCoF", 
       "legend"  : None, 
       "filter"  : [("A_CODE"    , '==', 0),
                    ("Contigence", '>' , 9),
                    ("Contigence", '<=', 18)]}],


    'Distribuição do RoCoF por Contingência [19 a 27]' :
     [{"x"       : "Contigence", 
       "y"       : "A_RCFC", 
       "c"       : "", 
       "plot"    : "Violin", 
       "round"   : "",
       "stat"    : "",
       "x_label" : "Contingência",
       "y_label" : "RoCoF", 
       "legend"  : None, 
       "filter"  : [("A_CODE"    , '==', 0),
                    ("Contigence", '>' , 18),
                    ("Contigence", '<=', 27)]}],

    'Distribuição do RoCoF por Contingência [28 a 36]' : 
     [{"x"       : "Contigence", 
       "y"       : "A_RCFC", 
       "c"       : "", 
       "plot"    : "Violin", 
       "round"   : "",
       "stat"    : "",
       "x_label" : "Contingência",
       "y_label" : "RoCoF", 
       "legend"  : None, 
       "filter"  : [("A_CODE"    , '==', 0),
                    ("Contigence", '>' , 27),
                    ("Contigence", '<=', 36)]}],

    'Distribuição do RoCoF por Contingência [37 a 45]' : 
     [{"x"       : "Contigence", 
       "y"       : "A_RCFC", 
       "c"       : "", 
       "plot"    : "Violin", 
       "round"   : "",
       "stat"    : "",
       "x_label" : "Contingência",
       "y_label" : "RoCoF", 
       "legend"  : None, 
       "filter"  : [("A_CODE"    , '==', 0),
                    ("Contigence", '>' , 36),
                    ("Contigence", '<=', 45)]}],

    'Distribuição do RoCoF por Contingência [46 a 51]' : 
     [{"x"       : "Contigence", 
       "y"       : "A_RCFC", 
       "c"       : "", 
       "plot"    : "Violin", 
       "round"   : "",
       "stat"    : "",
       "x_label" : "Contingência",
       "y_label" : "RoCoF", 
       "legend"  : None, 
       "filter"  : [("A_CODE"    , '==', 0),
                    ("Contigence", '>' , 45),
                    ("Contigence", '<=', 51)]}],                  

    },
    
    'NADIR' : {

    'Distribuição do Frequência de Nadir por Contingência [1 a 9]' :
    [{"x"       : "Contigence", 
       "y"       : "A_NDRC", 
       "c"       : "", 
       "plot"    : "Violin", 
       "round"   : "",
       "stat"    : "",
       "x_label" : "Contingência",
       "y_label" : "Frequência de Nadir", 
       "legend"  : None, 
       "filter"  : [("A_CODE"    , '==', 0),
                    ("Contigence", '>' , 0),
                    ("Contigence", '<=', 9)]}],

    'Distribuição do Frequência de Nadir por Contingência [10 a 18]' :
     [{"x"       : "Contigence", 
       "y"       : "A_NDRC", 
       "c"       : "", 
       "plot"    : "Violin", 
       "round"   : "",
       "stat"    : "",
       "x_label" : "Contingência",
       "y_label" : "Frequência de Nadir", 
       "legend"  : None, 
       "filter"  : [("A_CODE"    , '==', 0),
                    ("Contigence", '>' , 9),
                    ("Contigence", '<=', 18)]}], 

    'Distribuição do Frequência de Nadir por Contingência [19 a 27]' :
    [{"x"       : "Contigence", 
       "y"       : "A_NDRC", 
       "c"       : "", 
       "plot"    : "Violin", 
       "round"   : "",
       "stat"    : "",
       "x_label" : "Contingência",
       "y_label" : "Frequência de Nadir", 
       "legend"  : None, 
       "filter"  : [("A_CODE"    , '==', 0),
                    ("Contigence", '>' , 18),
                    ("Contigence", '<=', 27)]}],  

    'Distribuição do Frequência de Nadir por Contingência [28 a 36]' :
    [{"x"       : "Contigence", 
       "y"       : "A_NDRC", 
       "c"       : "", 
       "plot"    : "Violin", 
       "round"   : "",
       "stat"    : "",
       "x_label" : "Contingência",
       "y_label" : "Frequência de Nadir", 
       "legend"  : None, 
       "filter"  : [("A_CODE"    , '==', 0),
                    ("Contigence", '>' , 27),
                    ("Contigence", '<=', 36)]}], 

    'Distribuição do Frequência de Nadir por Contingência [37 a 45]' :
    [{"x"       : "Contigence", 
       "y"       : "A_NDRC", 
       "c"       : "", 
       "plot"    : "Violin", 
       "round"   : "",
       "stat"    : "",
       "x_label" : "Contingência",
       "y_label" : "Frequência de Nadir", 
       "legend"  : None, 
       "filter"  : [("A_CODE"    , '==', 0),
                    ("Contigence", '>' , 36),
                    ("Contigence", '<=', 45)]}], 

    'Distribuição do Frequência de Nadir por Contingência [46 a 51]' :
    [{"x"       : "Contigence", 
       "y"       : "A_NDRC", 
       "c"       : "", 
       "plot"    : "Violin", 
       "round"   : "",
       "stat"    : "",
       "x_label" : "Contingência",
       "y_label" : "Frequência de Nadir", 
       "legend"  : None, 
       "filter"  : [("A_CODE"    , '==', 0),
                    ("Contigence", '>' , 45),
                    ("Contigence", '<=', 51)]}],                     

    }}